title: CoderDojoHawthorn
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  CoderDojo is an initiative to educate young children between the ages of 7 and 17 about coding in various languages. These languages include Python, Javascript and many others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "coderdojohawthorn.tech" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
    style: compressed
# Other config
bgcolor: rgb(199, 207, 242)
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
